hexapod_controller:
  ros__parameters:

    # Configuration Settings

    # Number of Legs
    NUMBER_OF_LEGS: 6

    # Number of leg segments ( 3dof or 4dof )
    NUMBER_OF_LEG_SEGMENTS: 3

    # Define Initial Coxa Offsets in Radians ['RR', 'RM', 'RF', 'LR', 'LM', 'LF']
    # IK is solved in local space currently, hence the reason right and left have same angle offsets.
    INIT_COXA_ANGLE: [-60.0, 0.0, 60.0, -60.0, 0.0, 60.0]

    # Define distance in meters from coxa joint to the center ['RR', 'RM', 'RF', 'LR', 'LM', 'LF']
    # IK is solved in local space currently, hence the reason right and left have same distance values
    COXA_TO_CENTER_X: [-0.128895, 0.006895, 0.114925, -0.128895, 0.006895, 0.114925]
    COXA_TO_CENTER_Y: [-0.06091, -0.1035, -0.06091, 0.06091, 0.1035, 0.06091]
    INIT_FOOT_POS_X: [-0.25, 0.0, 0.25, -0.25, 0.0, 0.25]
    INIT_FOOT_POS_Y: [-0.23, -0.308, -0.23, 0.23, 0.308, 0.23]
    INIT_FOOT_POS_Z: 0.09

    # Servo limits in Ticks, measured
    LIMIT_COXA: [237, 775]
    LIMIT_FEMUR: [190, 822]
    LIMIT_TIBIA: [325, 735]

    # Define Leg Measurements in meters
    COXA_LENGTH:   0.052
    FEMUR_LENGTH:  0.0645
    TIBIA_LENGTH:  0.133

    # Body FK maximum rotation
    BODY_MAX_ROLL: !degrees 8
    BODY_MAX_PITCH: !degrees 8

    # Body Standing Height
    STANDING_BODY_HEIGHT: 0.06

    # Gait Settings
    SUB_STEPS: 50.0
    LEG_LIFT_HEIGHT: 0.038
    MAX_LIFT_HEIGHT: 0.050

    # Servo descriptions
    ## Servo names, required since multi dimensional arrays are not supported in ROS2 as of now
    SERVO_NAMES: [COXA_RR, FEMUR_RR, TIBIA_RR, COXA_RM, FEMUR_RM, TIBIA_RM, COXA_RF, FEMUR_RF, TIBIA_RF, COXA_LR, FEMUR_LR, TIBIA_LR, COXA_LM, FEMUR_LM, TIBIA_LM, COXA_LF, FEMUR_LF, TIBIA_LF]
    # Test Servos
    # SERVO_NAMES: [COXA_TEST, FEMUR_TEST, TIBIA_TEST]

    ## NR, ID, Ticks, Center, Max_Degree, Sign, Offset
    COXA_RR:  [ 1,  8, 1024, 506, 300, -1, 0]
    FEMUR_RR: [ 2, 10, 1024, 506, 300, -1, 0]
    TIBIA_RR: [ 3, 12, 1024, 506, 300,  1, 0]

    COXA_RM:  [ 4, 14, 1024, 506, 300, -1, 0]
    FEMUR_RM: [ 5, 16, 1024, 506, 300, -1, 0]
    TIBIA_RM: [ 6, 18, 1024, 506, 300,  1, 0]

    COXA_RF:  [ 7,  2, 1024, 506, 300, -1, 0]
    FEMUR_RF: [ 8,  4, 1024, 506, 300, -1, 0]
    TIBIA_RF: [ 9,  6, 1024, 506, 300,  1, 0]

    COXA_LR:  [10,  9, 1024, 506, 300,  1, 0]
    FEMUR_LR: [11, 11, 1024, 506, 300, -1, 0]
    TIBIA_LR: [12, 13, 1024, 506, 300,  1, 0]

    COXA_LM:  [13, 15, 1024, 506, 300,  1, 0]
    FEMUR_LM: [14, 17, 1024, 506, 300, -1, 0]
    TIBIA_LM: [15, 19, 1024, 506, 300,  1, 0]

    COXA_LF:  [16,  3, 1024, 506, 300,  1, 0]
    FEMUR_LF: [17,  5, 1024, 506, 300, -1, 0]
    TIBIA_LF: [18,  7, 1024, 506, 300,  1, 0]


    COXA_TEST:  [1, 40, 1024, 512, 300,  1, 0]
    FEMUR_TEST: [2, 41, 1024, 512, 300, -1, 0]
    TIBIA_TEST: [3, 42, 1024, 512, 300,  1, 0]
